options:
    machineType: N1_HIGHCPU_32
substitutions:
    _REPO: gcr.io/yus-demo

steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build
  args: ['build', '--cache-from', 'master:latest', '-t', '$_REPO/$BRANCH_NAME:latest', '.']

- name: gcr.io/cloud-builders/docker
  id: docker-push
  args: ['push', '$_REPO/$BRANCH_NAME:latest']

- name: gcr.io/cloud-builders/kubectl
  id: deploy-infrastructure
  env: ['CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a', 'CLOUDSDK_CONTAINER_CLUSTER=features']
  entrypoint: bash
  args:
  - '-c'
  - |
    cd gcp
    sed -e "s|_BRANCH_NAME|$BRANCH_NAME|g" deployment.yaml | tee deployment2.yaml
    gcloud container clusters get-credentials --project="yus-demo" --zone="australia-southeast1-a" "features"
    kubectl apply -f deployment2.yaml

images: ['$_REPO/$BRANCH_NAME:latest']
