options:
    machineType: N1_HIGHCPU_32
substitutions:
    _REPO: gcr.io/yus-demo

steps:
- name: ubuntu
  id: generate-image-tag
  entrypoint: bash
  args:
  - '-c'
  - echo $(date) | md5sum | awk '{print $1}' > tag.txt

- name: gcr.io/cloud-builders/docker
  id: docker-build
  entrypoint: bash
  args:
  - '-c'
  - |
    tag=`cat tag.txt`
    echo tag=$tag
    docker build -t "$_REPO/$BRANCH_NAME:$tag" .
    docker push "$_REPO/$BRANCH_NAME:$tag"

- name: gcr.io/cloud-builders/kubectl
  id: deploy-infrastructure
  env: ['CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a', 'CLOUDSDK_CONTAINER_CLUSTER=features']
  entrypoint: bash
  args:
  - '-c'
  - |
    tag=`cat tag.txt`
    cd gcp
    sed -e "s|_BRANCH_NAME|$BRANCH_NAME|g" -e "s|_TAG|$tag|g" deployment.yaml | tee deployment2.yaml
    gcloud container clusters get-credentials --project="yus-demo" --zone="australia-southeast1-a" "features"
    kubectl apply -f deployment2.yaml
