kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: _BRANCH_NAME-deployment
  labels:
    branchName: _BRANCH_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      branchName: _BRANCH_NAME
  template:
    metadata:
      labels:
        branchName: _BRANCH_NAME
    spec:
      containers:
      - name: _BRANCH_NAME
        image: gcr.io/yus-demo/_BRANCH_NAME:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: _BRANCH_NAME-service
  labels:
    branchName: _BRANCH_NAME
spec:
  selector:
    branchName: _BRANCH_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
